# fly.toml file generated for alex-spring-boot-flyio on 2023-04-09T15:01:25+02:00

app = "alex-spring-boot-flyio"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"
processes = []

[build]
  image = "ghcr.io/alexandredepape/spring-boot-flyio:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8098
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
